version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - gocritic

issues:
  exclude-dirs:
    - internal/server/webdist
